### PR TITLE
 KD-10081 | omniauth-microsoft-update-dependencies

### PR DESCRIPTION
**Pull request by K-Semchenko**
was needed to update this dependencies to have option to update omniauth gem in kudos 
[https://kudoswork.atlassian.net/browse/KD-10047](https://kudoswork.atlassian.net/browse/KD-10047)

### CODE REVIEW

**Comment by jessie-kudos** [comment]
Can you please update the PR title?

**Comment by K-Semchenko** [comment]
> Can you please update the PR title?

Done

**Review by jessie-kudos — APPROVED** [review]
LGTM

**Comment by K-Semchenko** [comment]
No need, as we are not updating omniauth for now

**Pull request closed without merging**
